### PR TITLE
Build improvments

### LINKED ISSUE #77: Add version information in builds
In preparation to move towards Beta and first official release need to embed version information with each build and move towards proper release management using milestones.

### PR DESCRIPTION
**Pull request by cosmincojocar**
- Add a Makefile which automates the common build tasks 
- Introduce the build information which is injected during build with the help of linker flags
- Switch from godep to dep for dependencies management 
- Update the build to use the make test target
- Update the Dockerfile to make easier the usage of gas running in docker container
- Add the Development section to README file
- Add Go 1.10 to the build and drop the support for 1.7

Fixes #77

cc @gcmurphy

### CODE REVIEW

**Comment by gcmurphy** [comment]
This is looking really nice. I'll try to review this properly soon.

**Comment by gcmurphy** [comment]
@cosmincojocar tried to review this but am hitting a weird error on my Mac. 
(see https://github.com/golang/dep/issues/1738)

If you've got any ideas what I'm messing up let me know.

**Comment by gcmurphy** [comment]
Happy with these changes but want to wait until https://github.com/mozilla/tls-observatory/pull/306 or another suitable fix is merged into the mozilla's tls observatory.

**Comment by cosmincojocar** [comment]
@gcmurphy Thanks for following up the build issue with the `tls-observatory`. It seems that is fixed now. I tried on my Mac, and it works.

**Comment by gcmurphy** [comment]
Great thanks for following up!

**Pull request merged**
