### PR TITLE
Add a semantic version to the usage text

### PR DESCRIPTION
**Pull request by cosmincojocar**
Fix for #77 

cc @gcmurphy

### CODE REVIEW

**Comment by gcmurphy** [comment]
Thanks this looks good and will help with debugging issues. I'm wondering if we could pass this in somehow at build time rather than hardcoding it? Similar to this https://medium.com/@joshroppo/setting-go-1-5-variables-at-compile-time-for-versioning-5b30a965d33e or maybe we should investigate using something like https://github.com/ahmetb/govvv 

I'd like to start using git tags and doing proper releases soon.

**Comment by cosmincojocar** [comment]
These approaches seem interesting. I'll have a look to them.

I am also working on a Makefile which will automate the build, test, release and docker image build steps. The script will get the version from the latest git tag as follows:

```
VERSION ?= $(shell git describe --always --tags)
BIN = gas
BUILD_CMD = go build -o build/$(BIN)-$(VERSION)-$${GOOS}-$${GOARCH} &
```
I hope to create a PR till tomorrow.

**Comment by cosmincojocar** [comment]
@gcmurphy I will follow up with the Makefile in a different PR

**Comment by cosmincojocar** [comment]
@gcmurphy I am closing this in favor of PR #179.

**Pull request closed without merging**
